Repository RIKI-05/MOMOMIA, pull requests merged in 2022-10, with the labels that each got.

#14 Add About us Section
  MOMOMIA/About us/About.css
  MOMOMIA/About us/About.html
  MOMOMIA/index.html
Labels: good first issue, hacktoberfest, hacktoberfest-accepted

#16 Revert "Add About us Section"
  MOMOMIA/About us/About.css
  MOMOMIA/About us/About.html
  MOMOMIA/index.html
Labels: bug, good first issue, hacktoberfest-accepted

#15 fix: Make the footer icons bigger
  MOMOMIA/styles.css
Labels: good first issue, hacktoberfest, hacktoberfest-accepted

#25 Added Animation
  Abhishek/About us/About.css
  Abhishek/About us/About.html
  Abhishek/Demo1.png
  Abhishek/Demo2.png
  Abhishek/images/beverages.jpg
  Abhishek/images/chinese.jpg
  Abhishek/images/momoMain.jpg
  Abhishek/images/momomi.png
  Abhishek/images/momomia.png
  Abhishek/images/momos.jpg
  Abhishek/images/non-veg.jpg
  Abhishek/images/veg.jpg
  Abhishek/index.html
  Abhishek/index.js
  Abhishek/styles.css
  Abhishek/svg/clean.svg
  Abhishek/svg/mask.svg
  Abhishek/svg/sanitizer.svg
  Abhishek/svg/thermo.svg
Labels: good first issue, hacktoberfest, hacktoberfest-accepted

#26 Issue 18 updated
  MOMOMIA/index.html
  MOMOMIA/styles.css
Labels: hacktoberfest, hacktoberfest-accepted

#30 Chnaged font and font size of MOMOMIA
  MOMOMIA/fonts/EMcomic-Bold.ttf
  MOMOMIA/index.html
  MOMOMIA/styles.css
Labels: good first issue, hacktoberfest, hacktoberfest-accepted

#31 Logo size
  MOMOMIA/index.html
Labels: good first issue, hacktoberfest, hacktoberfest-accepted

#36 Updated Animation on "order now" . issue #5
  MOMOMIA/styles.css
Labels: good first issue, hacktoberfest

#27 Improved look of Headings
  MOMOMIA/index.html
Labels: hacktoberfest-accepted

#39 Logo Size, social icons hover
  MOMOMIA/styles.css
Labels: good first issue, hacktoberfest, hacktoberfest-accepted

#47 Added few comments to understand code better
  MOMOMIA/index.html
Labels: good first issue, hacktoberfest, hacktoberfest-accepted

#46 Issue number 35
  MOMOMIA/images/landing.png
  MOMOMIA/images/momoss.png
  MOMOMIA/index.html
  MOMOMIA/styles.css
Labels: good first issue, hacktoberfest, hacktoberfest-accepted

#50 Font sized changed
  MOMOMIA/index.html
Labels: good first issue, hacktoberfest, hacktoberfest-accepted

#54 Inverted the colours of navbar
  MOMOMIA/index.html
Labels: good first issue, hacktoberfest, hacktoberfest-accepted

#56 Updated icon links & fixed hover effect
  MOMOMIA/index.html
  MOMOMIA/styles.css
Labels: good first issue, hacktoberfest, hacktoberfest-accepted

#68 Added the glow effect to the checkout button
  MOMOMIA/styles.css
Labels: hacktoberfest, hacktoberfest-accepted

#73 Readme updated
  README.md
Labels: good first issue, hacktoberfest, hacktoberfest-accepted

#76 Added zoom hover effect on homeImg
  MOMOMIA/styles.css
Labels: enhancement, good first issue, hacktoberfest, hacktoberfest-accepted

#80 Added Black color to scroll bar
  MOMOMIA/index.html
  MOMOMIA/styles.css
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#81 Grammatical errors fixed
  README.md
Labels: good first issue, hacktoberfest, hacktoberfest-accepted

#82 solved issue no #62
  MOMOMIA/index.html
  MOMOMIA/terms_of_service.css
  MOMOMIA/terms_of_service.html
Labels: good first issue, hacktoberfest, hacktoberfest-accepted

#86 Changed the color theme of Terms of Service page font: white page: black
  MOMOMIA/terms_of_service.css
Labels: good first issue, hacktoberfest, hacktoberfest-accepted

#88 favicon, meta tags, contact us linking, hover effects
  MOMOMIA/contactus.html
  MOMOMIA/images/momo-icon.png
  MOMOMIA/index.html
  MOMOMIA/styles.css
  MOMOMIA/terms_of_service.html
Labels: good first issue, hacktoberfest, hacktoberfest-accepted

#90 Extra items added
  MOMOMIA/index.html
Labels: good first issue, hacktoberfest-accepted

#100 cursor changes to hand pointer upon hovering a category
  MOMOMIA/styles.css
Labels: good first issue, hacktoberfest, hacktoberfest-accepted

#106 Add animation in text inebriates
  MOMOMIA/index.html
  MOMOMIA/styles.css
Labels: good first issue, hacktoberfest, hacktoberfest-accepted

#110 footer improved
  MOMOMIA/index.html
Labels: good first issue, hacktoberfest, hacktoberfest-accepted

#117 Enchanced the Cart UI
  MOMOMIA/index.html
  MOMOMIA/index.js
  MOMOMIA/styles.css
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#116 Improve Responsiveness
  MOMOMIA/index.html
  MOMOMIA/styles.css
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#118 Changed fonts of Monomia in navbar and footer.
  MOMOMIA/index.html
Labels: good first issue, hacktoberfest, hacktoberfest-accepted

#126 Hygiene section improvement
  MOMOMIA/index.html
  MOMOMIA/styles.css
Labels: good first issue, hacktoberfest, hacktoberfest-accepted

#125 added veg/non-veg symbol to cart modal
  MOMOMIA/index.html
  MOMOMIA/index.js
  MOMOMIA/styles.css
Labels: good first issue, hacktoberfest, hacktoberfest-accepted

#124 button of navbar active for the respective Section
  MOMOMIA/index.html
  MOMOMIA/index.js
Labels: good first issue, hacktoberfest, hacktoberfest-accepted

#121 Improved Terms of Services section with some UI/Colour/Format changes
  MOMOMIA/terms_of_service.css
  MOMOMIA/terms_of_service.html
Labels: good first issue, hacktoberfest, hacktoberfest-accepted

#135 whatsapp icon and googlepay added
  MOMOMIA/index.html
  MOMOMIA/styles.css
Labels: good first issue, hacktoberfest, hacktoberfest-accepted

#142 Navbar added in terms of service page
  MOMOMIA/terms_of_service.css
  MOMOMIA/terms_of_service.html
Labels: good first issue, hacktoberfest, hacktoberfest-accepted

#152 social media animation added
  MOMOMIA/styles.css
Labels: good first issue, hacktoberfest, hacktoberfest-accepted

#147 Added footer navigation
  MOMOMIA/contactus.html
  MOMOMIA/index.html
  MOMOMIA/terms_of_service.html
Labels: good first issue, hacktoberfest, hacktoberfest-accepted

#148 Added an aesthetic loader for the website.
  MOMOMIA/index.html
  MOMOMIA/styles.css
Labels: enhancement, hacktoberfest

#156 Update styles.css
  MOMOMIA/styles.css
Labels: good first issue, hacktoberfest, hacktoberfest-accepted

#164 changed cart area color
  MOMOMIA/styles.css
Labels: good first issue, hacktoberfest, hacktoberfest-accepted

#168 New contact page UI
  MOMOMIA/contactus.css
  MOMOMIA/contactus.html
  MOMOMIA/images/left.jpg
Labels: good first issue, hacktoberfest, hacktoberfest-accepted

#170 Contact us footer
  MOMOMIA/contactus.css
  MOMOMIA/contactus.html
  MOMOMIA/icons/email.gif
  MOMOMIA/icons/maps.gif
  MOMOMIA/icons/phone.gif
  MOMOMIA/images/backgroundjpg.jpg
  MOMOMIA/images/bg.jpg
  MOMOMIA/nav.css
Labels: enhancement, good first issue, hacktoberfest, hacktoberfest-accepted

#173 changed navbar style for mobile width and terms page
  MOMOMIA/styles.css
  MOMOMIA/terms_of_service.css
Labels: good first issue, hacktoberfest, hacktoberfest-accepted

#174 Many bugs fixed
  MOMOMIA/index.html
  MOMOMIA/index.js
  MOMOMIA/styles.css
Labels: good first issue, hacktoberfest, hacktoberfest-accepted

#176 Create LICENSE
  LICENSE
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#177 Added Navbar, Increased Icon Size, Increased Text Size :D
  MOMOMIA/contactus.css
  MOMOMIA/contactus.html
  MOMOMIA/index.html
  MOMOMIA/nav.css
Labels: good first issue, hacktoberfest, hacktoberfest-accepted

#200 Improved the UI of Send Message box
  MOMOMIA/contactus.css
Labels: good first issue, hacktoberfest, hacktoberfest-accepted

#209 Revert "Improved the UI of Send Message box"
  MOMOMIA/contactus.css
Labels: good first issue, hacktoberfest

#208 Update index.html
  MOMOMIA/index.html
Labels: good first issue, hacktoberfest, hacktoberfest-accepted

#214 aligned menu at proper position
  MOMOMIA/contactus.css
  MOMOMIA/contactus.html
  MOMOMIA/styles.css
Labels: good first issue, hacktoberfest

#210 updated the readme
  README.md
Labels: good first issue, hacktoberfest

#217 Removed horizontal scrolling on Contact Us Page
  MOMOMIA/nav.css
Labels: good first issue, hacktoberfest, hacktoberfest-accepted

#215 Added Testimonials Section
  MOMOMIA/index.html
  MOMOMIA/styles.css
Labels: good first issue, hacktoberfest, hacktoberfest-accepted

#218 added responsiveness in contractus page for medium devices
  MOMOMIA/contactus.css
  MOMOMIA/contactus.html
  MOMOMIA/nav.css
Labels: good first issue, hacktoberfest-accepted

#219 I've Created contributing.md file
  CONTRIBUTING.md
Labels: good first issue, hacktoberfest

#222 Changed position of cart icon
  MOMOMIA/index.html
  MOMOMIA/index.js
  MOMOMIA/styles.css
Labels: good first issue, hacktoberfest, hacktoberfest-accepted
