Repository RIKI-05/MOMOMIA, pull requests merged in 2023-10, with the labels that each got.

#232 Responsiveness and some basic chnages
  MOMOMIA/index.html
  MOMOMIA/styles.css
Labels: good first issue, hacktoberfest-accepted

#233 Update contactus.html
  MOMOMIA/contactus.html
Labels: good first issue, hacktoberfest-accepted

#234 Update index.js
  MOMOMIA/index.js
Labels: hacktoberfest, hacktoberfest-accepted

#235 Revert "Update index.js"
  MOMOMIA/index.js
Labels: wontfix, hacktoberfest-accepted

#240 Fixed issue #237
  MOMOMIA/index.js
Labels: hacktoberfest-accepted

#242 Fixed issue 241
  MOMOMIA/index.html
Labels: hacktoberfest-accepted

#243 Update README.md
  README.md
Labels: good first issue, hacktoberfest-accepted

#245 Update contactus.html
  MOMOMIA/contactus.html
Labels: good first issue, hacktoberfest-accepted

#246 Update index.html
  MOMOMIA/index.html
Labels: good first issue, hacktoberfest-accepted

#244 Update CONTRIBUTING.md
  CONTRIBUTING.md
Labels: good first issue, hacktoberfest-accepted
